services:
  - type: web
    name: chatroom-frontend
    runtime: node
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: url
        value: mongodb+srv://vaishnaviienp:rZHzOod4oOXgouYL@cluster0.jmnwyfx.mongodb.net/
  - type: web
    name: chatroom-backend
    runtime: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: url
        value: mongodb+srv://vaishnaviienp:rZHzOod4oOXgouYL@cluster0.jmnwyfx.mongodb.net/
      - key: JWT_SECRET
        value: jwebthb
